// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoZc7VJeVad76OmCK0QM_aPFosjK3V0L8',
    appId: '1:986525426380:android:865324e4e829dce4d5d869',
    messagingSenderId: '986525426380',
    projectId: 'health-diagnosis-94ee9',
    databaseURL: 'https://health-diagnosis-94ee9-default-rtdb.firebaseio.com',
    storageBucket: 'health-diagnosis-94ee9.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLRQbUtaWBP1iRMXJQ8cwr9wfbhwdLHpA',
    appId: '1:986525426380:web:39f3e6e5a46f14f3d5d869',
    messagingSenderId: '986525426380',
    projectId: 'health-diagnosis-94ee9',
    authDomain: 'health-diagnosis-94ee9.firebaseapp.com',
    databaseURL: 'https://health-diagnosis-94ee9-default-rtdb.firebaseio.com',
    storageBucket: 'health-diagnosis-94ee9.appspot.com',
  );
}
